'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RetailwareImports.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Gear_Alt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Gear_Alt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE [dbo].[Proc_Import_NewItems] @FilePath nvarchar(500), @Server nvarchar(50), @Database nvarchar(50), @UserName nvarchar(50), @Password nvarchar(50)
        '''AS
        '''    IF OBJECT_ID(&apos;dbo.tmpImportNewItems&apos;, &apos;U&apos;) IS NOT NULL DROP TABLE dbo.tmpImportNewItems
        '''
        '''    CREATE TABLE [dbo].tmpImportNewItems(
        '''        [Itemcode] [nvarchar](100) NULL,
        '''        [Description] [nvarchar](500) NULL,
        '''        [ExtendedDesc] [nvarchar](500) NULL,
        '''        [Department] [nvarchar](500) NULL,
        '''        [Category] [nvarchar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Proc_Import_NewItems() As String
            Get
                Return ResourceManager.GetString("Proc_Import_NewItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE [dbo].[Proc_Import_NewItemsProcess] @IsResto nvarchar(5)
        '''AS
        '''	DECLARE @MaxID int = 0
        '''
        '''	SET @MaxID = (SELECT ISNULL(MAX(ID),0) FROM Department)
        '''	ALTER TABLE Department ALTER COLUMN [Code] [nvarchar](50) NOT NULL;
        '''	INSERT INTO Department SELECT NULL, LTRIM(RTRIM(Department)), @MaxID + ROW_NUMBER() OVER (ORDER BY Department ASC), 0, 1, NULL FROM ImportNewItems WHERE ISNULL(DepartmentID,&apos;&apos;) = &apos;&apos; GROUP BY Department
        '''	UPDATE a SET DepartmentID = b.ID FROM ImportNewItems a JOIN Department b  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Proc_Import_NewItemsProcess() As String
            Get
                Return ResourceManager.GetString("Proc_Import_NewItemsProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE [dbo].[Proc_Import_NewItemsValidate] @IsResto nvarchar(5)
        '''AS 
        '''    UPDATE a SET DepartmentID = b.ID FROM ImportNewItems a LEFT OUTER JOIN Department b on LTRIM(RTRIM(a.Department)) = LTRIM(RTRIM(b.Name))
        '''    UPDATE a SET CategoryID = b.ID FROM ImportNewItems a LEFT OUTER JOIN Category b on a.DepartmentID = b.DepartmentID AND LTRIM(RTRIM(a.Category)) = LTRIM(RTRIM(b.Name))
        '''    UPDATE a SET SubCategoryID = b.ID FROM ImportNewItems a LEFT OUTER JOIN SubCategory b on a.CategoryID = b.Categor [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Proc_Import_NewItemsValidate() As String
            Get
                Return ResourceManager.GetString("Proc_Import_NewItemsValidate", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
